#ifndef BOLODEMILHO_GLOBAL_H
#define BOLODEMILHO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BOLODEMILHO_LIBRARY)
#  define BOLODEMILHOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BOLODEMILHOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BOLODEMILHO_GLOBAL_H
