#ifndef BOLODECORATOR_GLOBAL_H
#define BOLODECORATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BOLODECORATOR_LIBRARY)
#  define BOLODECORATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BOLODECORATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BOLODECORATOR_GLOBAL_H
