#ifndef CALDADECHOCOLATE_GLOBAL_H
#define CALDADECHOCOLATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALDADECHOCOLATE_LIBRARY)
#  define CALDADECHOCOLATESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CALDADECHOCOLATESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CALDADECHOCOLATE_GLOBAL_H
