#ifndef CHOCOLATEGRANULADO_GLOBAL_H
#define CHOCOLATEGRANULADO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CHOCOLATEGRANULADO_LIBRARY)
#  define CHOCOLATEGRANULADOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CHOCOLATEGRANULADOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CHOCOLATEGRANULADO_GLOBAL_H
